import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Topbar from "../components/ui/topbar";
import Sidebar from "../components/ui/sidebar"
import { NotificationProvider } from "@/components/ui/notifications";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased dark inline-block bg-background`}
      >
        <div className="flex h-screen w-screen">
          {/* Sidebar */}
          <Sidebar />

          {/* Main content area */}
          <main className="flex-1 p-4 pl-0">
            <div className="bg-white rounded-lg h-full w-full p-6">
              <NotificationProvider>
                {children}
              </NotificationProvider>
            </div>
          </main>
        </div>
      </body>
    </html>
  );
}